TRAINING_FORWARDER_VERSION = 0.2.0
TRAINING_FORWARDER_SITE = $(call github,Exein-io,training-forwarder,v$(TRAINING_FORWARDER_VERSION))

TENSORFLOW_LITE_LICENSE = GPL-3.0
TENSORFLOW_LITE_LICENSE_FILES = LICENSE

TRAINING_FORWARDER_INSTALL_STAGING = NO


define TRAINING_FORWARDER_BUILD_CMDS
	$(MAKE) $(TARGET_CONFIGURE_OPTS) -C $(@D)
endef


define TRAINING_FORWARDER_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/training-forwarder $(TARGET_DIR)/usr/bin/exein-forward


$(eval $(generic-package))
